# Generated by Django 3.0 on 2025-02-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grades", "0027_favourite"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="pass_rate",
            field=models.FloatField(default=0),
        ),
    ]
