name: Lint

on: [push]

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Test
        run: uv run python manage.py test


  lint-black:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5


      - name: Run black
        run: uv run ruff check grades grades_api grades_api_v2 gradestats scripts clients

  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Check migrations
        env:
          DJANGO_SETTINGS_MODULE: gradestats.settings.dev
        run: uv run python manage.py makemigrations --check
